### ISSUE TITLE
Implement Authentication and Cloud DB

### ISSUE THREAD

**Issue by kithe-raker** [Bualoitech/learnliko#12]
To be able to track learner's progress and collecting information about them. The application is required to implement the following system
- [x] Authentication
For the sake of demo day, just use Guest account feature of Firebase
- [x] Cloud DB
To collect learner's progress and profile

**Comment by kithe-raker** [comment]
I genuinely forget about Firestore security, to make a request from client to the db securely, we have to 
1. set Firestore rule to false
2. on learnliko server, use Firebase Admin to make request to db

by apply this approach, it allow us to perform security check manually and customizable on the learnliko server rather than allow use to make a request to db directly/

**Comment by kithe-raker** [comment]
But again for the sake of Demo day, I will skip those step for now.
And perform a request to db directly on the client side

**Comment by athensclub** [comment]
Are you going to implement all functions in `localdb `folder for the demo day?

**Comment by kithe-raker** [comment]
> Are you going to implement all functions in `localdb `folder for the demo day?

That's look like a lot of work though, plus I haven't design the whole db's structure yet, so that would be after the demo day

**Comment by kithe-raker** [comment]
Any problem implement `createAccount` function?

**Comment by athensclub** [comment]
Not at the moment
