### ISSUE TITLE
Immersive Conversation

### ISSUE THREAD

**Issue by kithe-raker** [Bualoitech/learnliko#4]
From the feedback provided in #2 , one of things to improve is student engagement, so we have discussed that in the conversation section, we'll make change to the **UI/UX** to make it feels more like japan **RPG's dialog** game to increase user's engagement throughout the process of communicate with AI.

![image](https://github.com/Bualoitech/learnliko/assets/54874488/72821037-d219-4533-9fcd-8d560785bb26)
![image](https://github.com/Bualoitech/learnliko/assets/54874488/6471e454-8b6e-40ff-b312-db8dbd75b699)

And to make it more immersive, we also have to give AI the ability to express their feeling, plus lively roleplay

**Comment by kithe-raker** [comment]
To allow AI to perform a lively and immersive roleplay exp, I have found this platform, [Character.AI](https://beta.character.ai), its allow user to create and interact with AI that roleplay to be someone or something.
.
Seem to be a great example of how to create a better roleplay AI

**Comment by athensclub** [comment]
Currently got the UI too look like the following:
<img width="174" alt="image" src="https://github.com/Bualoitech/learnliko/assets/43963760/f7cfeb91-9fe5-4fd8-951f-a7cd3a53d8cd">
<img width="916" alt="image" src="https://github.com/Bualoitech/learnliko/assets/43963760/3f845334-b75f-4b5d-8122-9e17569b43fd">

All images are currently hardcoded in conversations.json

**Comment by kithe-raker** [comment]
To make roleplay AI able to express its emotion, we have to come up with a scope of how many emotion that AI can express
.
In this early stage, I think it will be best to use just the primary emotion. Therefore I will use the primary emotion refer from Robert Plutchik's wheel of emotions which will contains
- neutral(default)
- joy
- trust
- fear
- surprise
- sadness
- disgust
- anger
- anticipation
![image](https://github.com/Bualoitech/learnliko/assets/54874488/6e67ab7b-ea9c-457f-966d-f38e6f8736c1)
