### ISSUE TITLE
Improve Conversation system

### ISSUE THREAD

**Issue by kithe-raker** [Bualoitech/learnliko#8]
These are things that require to be improved

- [x] **CEFR base dialogue**
There are multi CEFR level of learner, so the dialog generate from role-play AI has to be adjust difficult base on learner's CEFR level
- [x] **Suggestion/Recap**
The algorithm to calculate learner's score are divided in 3 part, and can be describe as follow:
`Dialogue Score = Appropriateness * ( 50 + Grammar + Advancement )`
  - _Appropriateness(0,1)_
  Appropriateness of learner's response
  - _Grammar(0-20%)_
  Include example if learner's dialog is grammarly incorrect
  - _Advancement(0-30%)_
  depending on vocabulary and sentence structure of learner, if the level is lower than learner's CEFR level, include examples of vocabulary which is has the same advancement as learner's level
  
  >**NOTE:** In case learner has use hint, in that goal, learner will only received 40% of coin, and the score won't be used to calculate learner's CEFR
    
  To calculate goal score use the following equation:
  ```
  no hint used:
  Goal Score = sum(...Dialogue Score)/len(Dialogues)
  Coin Received = Goal Score

  hint used:
  Goal Score = 0
  Coin Received = 40
  ```

  To calculate conversation score(overall) use the following equation:
  ```
  Overall Score = sum(...Goal Score)/len(Goals)
  Total Coins = sum(Coin Received)
  ```

- [x] **Goal**
In goal section there are a few things to be improved
  - _Goal Tracking_
  When learner is talking to AI, we have to track conversation's goal and check whether they have complete each goal in the conversation.
  - _Context_
  Include details context of the conversation, so learner will be able to understand more about the situation
  - _Multi-Language_
  Right now only support Thai
- [x] **UI**
  - Before Enter and After Complete the conversation
  - Goal Transition
- [x] **Hint**
If the learner cannot reply to AI, they will be able to use hint, in exchange with decreased coin that they will received from that session

**Comment by kithe-raker** [comment]
After exit by using go back in `browser button` from playing conversation
<img width="905" alt="Screenshot 2566-06-23 at 18 55 22" src="https://github.com/Bualoitech/learnliko/assets/54874488/3b8e97fc-d260-48ac-9605-37e59f003a46">
.
This should handle prevent user from go back without confirm. Just gonna leave it here.
https://stackoverflow.com/questions/12381563/how-can-i-stop-the-browser-back-button-using-javascript

**Comment by athensclub** [comment]
I think a better approach might be to use a separate chatbox that only exist in `/conversation/play` page. Working on it.

**Comment by athensclub** [comment]
> I think a better approach might be to use a separate chatbox that only exist in `/conversation/play` page. Working on it. Although yes, we should ask for confirmation before going back.

I got distracted by something else, just got round to finishing it (24dba0202ab44cd0d3519264677130bd4f85fe3f and 8ad26ffa06caf5e342df32517214263549f0950e)

How's other part going?

**Comment by kithe-raker** [comment]
Finished `check goal progress` function for `Goal tracking`, and `text adaptor` for creating `CEFR base dialogue`

**Comment by athensclub** [comment]
I've implemented conversation using `check goal progress` function, but it seems to give inaccurate results. Please try it for yourself.

**Comment by kithe-raker** [comment]
> I've implemented conversation using `check goal progress` function, but it seems to give inaccurate results. Please try it for yourself.

saw you passing user's every dialogues
```ts
get(history).map(item => `${item.role === 'user' ? 'User' : ct.conversation.avatar.name}: ${item.transcription}`).join("\n")
```
I think just provided the latest one would make the job done, or it won't so that's why you have to passing every dialogue?

**Comment by athensclub** [comment]
How's hint and suggestion/recap going?

**Comment by kithe-raker** [comment]
> How's hint and suggestion/recap going?

The analyze dialogue function is having a very weird behavior. Working on it rn

**Comment by kithe-raker** [comment]
Implementation Example of new `analyze dialogue score` function
```ts
analyzeDialogueScore(
   'Welcome to the shop how can I help you?', // assistant message
   {
      message: "Are there any pens available?", // learner message
      CEFRLevel: 'C2' // learner's CEFR level
   },
   'You are in the stationery shop, You have to buy stationery from the shop keeper' // context
);

// return value
{
   appropriateness: boolean;
   grammar: number;
   advancement: { score: number; examples: string[] };
}
```

**Comment by kithe-raker** [comment]
I working on writing to calculate the `goal score` function using `analyze dialogue score` function, then will be able to create a calculate conversation overall score/Recap

**Comment by athensclub** [comment]
Can you implement using `analyzeDialogueScore` in place of the old function in `conversation.ts`? @kithe-raker

**Comment by athensclub** [comment]
Nvm, I'm gonna have to make it compatible with new recap ui anyway. I'm going to try doing this myself.

> Can you implement using `analyzeDialogueScore` in place of the old function in `conversation.ts`? @kithe-raker

**Comment by kithe-raker** [comment]
> > Can you implement using `analyzeDialogueScore` in place of the old function in `conversation.ts`? @kithe-raker
> 
> Nvm, I'm gonna have to make it compatible with new recap ui anyway. I'm going to try doing this myself.

sorry, just saw the nofi, I already implement it in the `global/conversation` in `computeRecap` function.
But I use the new data model though, so you will have to implement some part of app which using the `recapHistory`.
.
Rn I using following store obj to provide the recap result
```
export const recapResult = writable<RecapResult | null>();
```

**Comment by kithe-raker** [comment]
Boy, `global/conversation.ts` sure is a mess of spaghetti code

**Comment by athensclub** [comment]
What's the cause of this weird request? I got this after clicking `start conversation` in conversation card

<img width="290" alt="image" src="https://github.com/Bualoitech/learnliko/assets/43963760/6129decc-e7a2-441f-b9ba-bf4e5ab71597">

**Comment by kithe-raker** [comment]
> What's the cause of this weird request? I got this after clicking `start conversation` in conversation card
> 
> <img alt="image" width="290" src="https://user-images.githubusercontent.com/43963760/248579679-6129decc-e7a2-441f-b9ba-bf4e5ab71597.png">

was gonna ask you the same thing

**Comment by athensclub** [comment]
> > What's the cause of this weird request? I got this after clicking `start conversation` in conversation card
> > <img alt="image" width="290" src="https://user-images.githubusercontent.com/43963760/248579679-6129decc-e7a2-441f-b9ba-bf4e5ab71597.png">
> 
> was gonna ask you the same thing

![image](https://github.com/Bualoitech/learnliko/assets/43963760/669b539a-aea9-4ec6-b584-3e7dfdc9aafd)

**Comment by athensclub** [comment]
Required before demo (< 10hrs away)
 - [ ] keyboard shortcut to simulate passing conversation goal.
 - [ ] conversation card in `/conversation` page does not has typewriter effect and adjust font sizing.
 - [ ] reading data based on CEFR level
